name = "HermiteInterpolation"
uuid = "e59a9049-0778-4b41-b4a6-c75571210bee"
authors = ["Kipton Barros <kbarros@gmail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1.10"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff"]
